profiles:
  bh22-windows-192.168.56.111:
    connector: stix_bundle
    connection:
      host: http://localhost:6001/bh22_windows_192_168_56_111.json
    config:
      auth:
        username:
        password:
  bh22-windows-192.168.56.112:
    connector: stix_bundle
    connection:
      host: http://localhost:6001/bh22_windows_192_168_56_112.json
    config:
      auth:
        username:
        password:
  bh22-linux-192.168.56.91:
    connector: stix_bundle
    connection:
      host: http://localhost:6001/bh22_linux_192_168_56_91.json
    config:
      auth:
        username:
        password:
